server:
  port: 8030

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/itemlist
    driver-class-name: org.mariadb.jdbc.Driver
    username: bootuser
    password: 1234


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace